name: Upgrade

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+"
defaults:
  run:
    shell: bash
    working-directory: metallboperator

jobs:
  main:
    runs-on: ubuntu-20.04
    env:
      built_image_prev_release: "metallb-operator-prev-rel:ci" # Arbitrary name
      built_image: "metallb-operator:ci" # Arbitrary name
    strategy:
      matrix:
        go: [ '1.17' ] # this need to stay to 1.17 as long as the previous release is v0.12
    name: Go ${{ matrix.go }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Checkout Previous Release Metal LB Operator
      uses: actions/checkout@v4
      with:
        path: metallboperator
        ref: v0.12 # previous release version
        fetch-depth: 0 # Fetch all history for all tags and branches

    - uses: actions/setup-go@v5
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Build image
      run: |
        IMG=${built_image_prev_release} make docker-build
    - name: Create K8s Kind Cluster
      run: |
        ./hack/kind-cluster-without-registry.sh
        kind load docker-image ${built_image_prev_release}
    - name: Deploy Previous Release Metal LB Operator
      run: |
        make deploy-cert-manager
        IMG=${built_image_prev_release} KUSTOMIZE_DEPLOY_DIR="config/kind-ci/" ENABLE_OPERATOR_WEBHOOK="true" make deploy
    - name: E2E Tests
      run: |
        export KUBECONFIG=${HOME}/.kube/config
        make test-validation
        make test-e2e
    - name: Archive E2E Tests logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test_e2e_logs
        path: /tmp/test_e2e_logs/
    - name: Export kind logs
      if: ${{ failure() }}
      run: |
        kind export logs /tmp/kind_logs
    - name: Archive kind logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: kind_logs
        path: /tmp/kind_logs

    - name: Checkout Latest Metal LB Operator
      uses: actions/checkout@v4
      with:
        path: metallboperator-latest
        fetch-depth: 0 # Fetch all history for all tags and branches
    - name: Build image
      run: |
        cd ${GITHUB_WORKSPACE}/metallboperator-latest
        IMG=${built_image} make docker-build
        kind load docker-image ${built_image}
    - name: Deploy Metal LB Operator
      run: |
        cd ${GITHUB_WORKSPACE}/metallboperator-latest
        IMG=${built_image} KUSTOMIZE_DEPLOY_DIR="config/kind-ci/"  make deploy
    - name: E2E Tests
      run: |
        cd ${GITHUB_WORKSPACE}/metallboperator-latest
        export KUBECONFIG=${HOME}/.kube/config
        make test-validation
        make test-e2e
    - name: Archive E2E Tests logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test_e2e_logs
        path: /tmp/test_e2e_logs/
    - name: Export kind logs
      if: ${{ failure() }}
      run: |
        kind export logs /tmp/kind_logs
    - name: Archive kind logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: kind_logs
        path: /tmp/kind_logs
